#!/usr/local/bin/python3

import sys
import csv

def readFile(file):
   with open(file, 'r') as f:
      csvfile = csv.reader(f)
      for row in csvfile:
         print(row)

def sysmodule():
   script, first, second = sys.argv
   print(f'This is the name of the script: {script}')
   print(f'This is the first arguement: {first}')
   print(f'This is the second arguement: {second}')


readFile(sys.argv[1])
